routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/diklat', 'DiklatController@index')->name('diklat');
Route::prefix('diklat')->name('diklat.')->group(function () {
    Route::get('/create', 'DiklatController@create')->name('create');
    Route::get('/{diklat}/edit', 'DiklatController@edit')->name('edit');
    Route::post('/delete/{diklat}', 'DiklatController@delete')->name('delete');
    Route::post('', 'DiklatController@store')->name('store');
    Route::post('/update/{diklat}', 'DiklatController@update')->name('update');
});

app/Diklat.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Diklat extends Model
{
    protected $table = 'diklat';

    const CREATED_AT = 'createdAt';
    const UPDATED_AT = 'updatedAt';

    protected $fillable = [
        'nama', 'jenis', 'penyelenggara',
        'jumlahPeserta', 'tanggalMulai', 'tanggalSelesai',
        'waktuMulai', 'waktuSelesai', 'durasi',
        'tempat', 'sertifikat', 'biaya',
        'kadaluarsaSertifikat', 'statusKadaluarsaSertifikat', 'deskripsi',
        'createdBy', 'updatedBy'
    ];

    public function getTanggalMulaiAttribute($tanggalMulai)
    {
        return Carbon::parse($tanggalMulai)->format('Y-m-d');
    }

    public function getTanggalSelesaiAttribute($tanggalSelesai)
    {
        return Carbon::parse($tanggalSelesai)->format('Y-m-d');
    }

    public function getKadaluarsaSertifikatAttribute($tanggalSelesai)
    {
        return Carbon::parse($tanggalSelesai)->format('Y-m-d');
    }

    public function setBiayaAttribute($biaya)
    {
        return $biaya ?? 0;
    }

    public function setWaktuMulaiAttribute($waktuMulai)
    {
        return $waktuMulai ?? '';
    }

    public function setWaktuSelesaiAttribute($waktuSelesai)
    {
        return $waktuSelesai ?? '';
    }

    public function setDeskripsiAttribute($deskripsi)
    {
        return $deskripsi ?? '';
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DiklatController.php
<?php

namespace App\Http\Controllers;

use App\Diklat;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class DiklatController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Diklat::query()
            ->select('id', 'nama', 'jenis', 'penyelenggara', 'jumlahPeserta', 'tanggalMulai', 'tanggalSelesai', 'durasi', 'tempat')
            ->latest();

            return DataTables::eloquent($data)
            ->addColumn('aksi', function($d) {
                $edit = route('diklat.edit', $d);
                return
                '<button  class="btn btn-sm btn-outline-primary my-1">Detail</button>
                <a href="'. $edit .'" class="btn btn-sm btn-outline-warning my-1">Edit</a>
                <button class="btn btn-sm btn-outline-danger my-1" onclick="showModal('.$d->id.')">Delete</button>';
            })
            ->editColumn('tanggalMulai', function ($d) {
                return Carbon::parse($d->tanggalMulai)->format('Y-m-d');
            })
            ->editColumn('tanggalSelesai', function ($d) {
                return Carbon::parse($d->tanggalSelesai)->format('Y-m-d');
            })
            ->rawColumns(['aksi'])
            ->addIndexColumn()
            ->toJson();
        }

        return view('diklat.index');
    }

    public function create()
    {
        return view('diklat.create');
    }

    public function store(Request $request)
    {
        $validatedData = $this->validateData($request);
        $mergedData = array_merge($validatedData, ['createdBy' => 1, 'updatedBy' => 1]);

        $diklat =  Diklat::create($mergedData);
        if ($request->statusKadaluarsaSertifikat == 1) {
            $diklat->statusKadaluarsaSertifikat = 1;
        } elseif ($request->kadaluarsaSertifikat) {
            $diklat->kadaluarsaSertifikat = $request->kadaluarsaSertifikat;
        }
        $diklat->save();
        session()->flash('message', 'Diklat Berhasil Ditambahkan');
        return redirect()->route('diklat');

    }

    public function edit(Diklat $diklat)
    {
        return view('diklat.edit', compact('diklat'));
    }

    public function update(Request $request, Diklat $diklat)
    {
        $validatedData = $this->validateData($request);

        $diklat->update($validatedData);
        if ($request->statusKadaluarsaSertifikat == 1) {
            $diklat->statusKadaluarsaSertifikat = 1;
        } elseif ($request->kadaluarsaSertifikat) {
            $diklat->kadaluarsaSertifikat = $request->kadaluarsaSertifikat;
        }
        $diklat->save();
        session()->flash('message', 'Diklat Berhasil Diedit');
        return redirect()->route('diklat');
    }

    private function validateData($data)
    {
        return $data->validate([
            'nama' => 'required',
            'jenis' => 'required',
            'deskripsi' => 'nullable|string',
            'penyelenggara' => 'required',
            'biaya' => 'nullable|numeric',
            'jumlahPeserta' => 'required',
            'kadaluarsaSertifikat' => 'nullable|date',
            'sertifikat' => 'required',
            'tanggalMulai' => 'required',
            'tanggalSelesai' => 'required',
            'waktuMulai' => 'nullable|string|date_format:H:i',
            'waktuSelesai' => 'nullable|string|date_format:H:i',
            'durasi' => 'required',
            'tempat' => 'nullable|string|max:255',
        ]);
    }

    public function delete(Diklat $diklat)
    {
        $diklat->delete();
        session()->flash('message', 'Data Berhasil Dihapus');
        return redirect()->back();
    }
}

resources/views/diklat/create.blade.php
@extends('layout.app')
@section('title', 'Tambah Diklat')
@section('page', 'Tambah Diklat')

@section('breadcumb')
    <li class="nav-item">
        <a class="nav-link disabled">></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{route('diklat')}}">Diklat</a>
    </li>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form method="POST" action="{{action('DiklatController@store')}}">
                        @csrf
                        <div class="row">
                            <div class="form-group col-sm-6">
                                <h3>Informasi Diklat</h3>
                                <div class="mb-3">
                                    <label for="nama">Nama Diklat <span class="text-danger"> *</span></label>
                                    <input name="nama" type="text" class="form-control" id="nama" placeholder="Nama Diklat" required value="{{old('nama')}}">
                                </div>
                                <div class="mb-3">
                                    <label for="jenis">Jenis </label><span class="text-danger"> *</span>
                                    <select name="jenis" class="select2bs4 custom-select" id="jenis" required>
                                        <option value="Internal">Internal</option>
                                        <option value="Eksternal">Eksternal</option>
                                    </select>
                                </div>
                                <div class="mb-3">
                                    <label for="deskripsi">Deskripsi</label>
                                    <input name="deskripsi" type="text" class="form-control" placeholder="Deskripsi" id="deskripsi" value="{{old('deskripsi')}}">
                                </div>
                                <div class="mb-3">
                                    <label for="penyelenggara">Penyelenggara </label><span class="text-danger"> *</span>
                                    <input name="penyelenggara" type="text" class="form-control" placeholder="Penyelenggara" id="penyelenggara" required value="{{old('penyelenggara')}}">
                                </div>
                                <div class="mb-3">
                                    <label for="biaya">Biaya</label>
                                    <input name="biaya" type="number" class="form-control" id="biaya" placeholder="Biaya" value="{{old('biaya')}}">
                                </div>
                                <div class="mb-3">
                                    <label for="jumlahPeserta">Jumlah Peserta </label><span class="text-danger"> *</span>
                                    <input name="jumlahPeserta" type="number" class="form-control" id="jumlahPeserta" placeholder="Jumlah Peserta" required value="{{old('jumlahPeserta')}}">
                                </div>
                                <div class="mb-3">
                                    <label for="kadaluarsaSertifikat">Tanggal Kadaluarsa Sertifikat</label>
                                    <div class="row">
                                        <div class="col-sm-7 pr-0">
                                            <input name="kadaluarsaSertifikat" type="date" class="form-control" id="kadaluarsaSertifikat" placeholder="Tanggal Kadaluarsa Sertifikat" value="{{old('kadaluarsaSertifikat')}}">
                                        </div>
                                        <div class="col-sm">
                                            <div class="form-check form-check-inline">
                                                <input class="form-check-input" type="checkbox" name="statusKadaluarsaSertifikat" id="statusKadaluarsaSertifikat" value="1" value="{{old('statusKadaluarsaSertifikat')}}">
                                                <label class="form-check-label" for="statusKadaluarsaSertifikat">Berlaku Selamanya</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <label for="sertifikat">Sertifikat </label><span class="text-danger"> *</span>
                                    <select name="sertifikat" class="select2bs4 custom-select" id="sertifikat" required>
                                        <option value="0">Tidak Ada</option>
                                        <option value="1">Ada</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group col">
                                <h3>Waktu dan Tempat</h3>
                                <div class="mb-3">
                                    <label for="tanggalMulai">Tanggal Diklat </label><span class="text-danger"> *</span>
                                    <input name="tanggalMulai" type="date" class="form-control" placeholder="Tanggal Diklat" id="tanggalMulai" required value="{{old('tanggalMulai')}}">
                                </div>
                                <div class="mb-3">
                                    <label for="tanggalSelesai">Tanggal Selesai </label><span class="text-danger"> *</span>
                                    <input name="tanggalSelesai" type="date" class="form-control" placeholder="Tanggal Selesai" id="tanggalSelesai" required value="{{old('tanggalSelesai')}}">
                                </div>
                                <div class="mb-3">
                                    <label for="waktuMulai">Waktu Mulai</label>
                                    <div class="row">
                                        <div class="col-sm-5">
                                            <input name="waktuMulai" type="time" class="form-control" id="waktuMulai" value="{{old('waktuMulai')}}">
                                        </div>
                                        <div class="col-sm-2">
                                            <label class="form-label my-1" for="waktuSelesai">Sampai</label>
                                        </div>
                                        <div class="col-sm">
                                            <input name="waktuSelesai" type="time" class="form-control" id="waktuSelesai" value="{{old('waktuSelesai')}}">
                                        </div>
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <label for="durasi">Durasi </label><span class="text-danger"> *</span>
                                    <input name="durasi" type="number" class="form-control" id="durasi" placeholder="Durasi" required value="{{old('durasi')}}">
                                </div>
                                <div class="mb-3">
                                    <label for="tempat">Lokasi</label>
                                    <input name="tempat" type="text" maxlength="255" class="form-control" placeholder="Lokasi" id="tempat" value="{{old('tempat')}}">
                                </div>
                                <div class="float-right mt-3">
                                    <button class="btn btn-primary" type="submit">Tambah</button>
                                    <a href="{{route('diklat')}}" class="btn btn-secondary">Batal</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    {{-- Sweetalert2 CDN --}}
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
        const kadaluarsaSertifikat = $('#kadaluarsaSertifikat');
        $('input[name="statusKadaluarsaSertifikat"]').change(function() {
            kadaluarsaSertifikat
            .attr('disabled', $('input[name="statusKadaluarsaSertifikat"]:checked').length == 1)
            .val($('input[name="statusKadaluarsaSertifikat"]:checked').length == 1 ? null : '');
        });
    </script>
    @if ($errors->any())
        <script>
            $(document).ready(function(){
                const error = '{{implode(" | ", $errors->all())}}';
                Swal.fire({
                    icon: "error",
                    title: "Error",
                    text: error,
                });
            });
        </script>
    @endif
@endpush

resources/views/diklat/edit.blade.php
@extends('layout.app')
@section('title', 'Edit Diklat')
@section('page', 'Edit Diklat')

@section('breadcumb')
    <li class="nav-item">
        <a class="nav-link disabled">></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{route('diklat')}}">Diklat</a>
    </li>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form method="POST" action="{{action('DiklatController@update', $diklat)}}">
                        @csrf
                        <div class="row">
                            <div class="form-group col-sm-6">
                                <h3>Informasi Diklat</h3>
                                <div class="mb-3">
                                    <label for="nama">Nama Diklat <span class="text-danger"> *</span></label>
                                    <input name="nama" type="text" class="form-control" id="nama" placeholder="Nama Diklat" required value="{{$diklat->nama}}">
                                </div>
                                <div class="mb-3">
                                    <label for="jenis">Jenis </label><span class="text-danger"> *</span>
                                    <select name="jenis" class="select2bs4 custom-select" id="jenis" required>
                                        <option value="Internal">Internal</option>
                                        <option value="Eksternal">Eksternal</option>
                                    </select>
                                </div>
                                <div class="mb-3">
                                    <label for="deskripsi">Deskripsi</label>
                                    <input name="deskripsi" type="text" class="form-control" placeholder="Deskripsi" id="deskripsi" value="{{$diklat->deskripsi ?? ''}}">
                                </div>
                                <div class="mb-3">
                                    <label for="penyelenggara">Penyelenggara </label><span class="text-danger"> *</span>
                                    <input name="penyelenggara" type="text" class="form-control" placeholder="Penyelenggara" id="penyelenggara" required value="{{$diklat->penyelenggara}}">
                                </div>
                                <div class="mb-3">
                                    <label for="biaya">Biaya</label>
                                    <input name="biaya" type="number" class="form-control" id="biaya" placeholder="Biaya" value="{{$diklat->biaya}}">
                                </div>
                                <div class="mb-3">
                                    <label for="jumlahPeserta">Jumlah Peserta </label><span class="text-danger"> *</span>
                                    <input name="jumlahPeserta" type="number" class="form-control" id="jumlahPeserta" placeholder="Jumlah Peserta" required value="{{$diklat->jumlahPeserta}}">
                                </div>
                                <div class="mb-3">
                                    <label for="kadaluarsaSertifikat">Tanggal Kadaluarsa Sertifikat</label>
                                    <div class="row">
                                        <div class="col-sm-7 pr-0">
                                            <input name="kadaluarsaSertifikat" type="date" class="form-control" id="kadaluarsaSertifikat" placeholder="Tanggal Kadaluarsa Sertifikat" value="{{$diklat->kadaluarsaSertifikat}}">
                                        </div>
                                        <div class="col-sm">
                                            <div class="form-check form-check-inline">
                                                <input class="form-check-input" type="checkbox" name="statusKadaluarsaSertifikat" id="statusKadaluarsaSertifikat" value="1" value="{{$diklat->statusKadaluarsaSertifikat}}">
                                                <label class="form-check-label" for="statusKadaluarsaSertifikat">Berlaku Selamanya</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <label for="sertifikat">Sertifikat </label><span class="text-danger"> *</span>
                                    <select name="sertifikat" class="select2bs4 custom-select" id="sertifikat" required>
                                        <option value="0">Tidak Ada</option>
                                        <option value="1">Ada</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group col">
                                <h3>Waktu dan Tempat</h3>
                                <div class="mb-3">
                                    <label for="tanggalMulai">Tanggal Diklat </label><span class="text-danger"> *</span>
                                    <input name="tanggalMulai" type="date" class="form-control" placeholder="Tanggal Diklat" id="tanggalMulai" required value="{{$diklat->tanggalMulai}}">
                                </div>
                                <div class="mb-3">
                                    <label for="tanggalSelesai">Tanggal Selesai </label><span class="text-danger"> *</span>
                                    <input name="tanggalSelesai" type="date" class="form-control" placeholder="Tanggal Selesai" id="tanggalSelesai" required value="{{$diklat->tanggalSelesai}}">
                                </div>
                                <div class="mb-3">
                                    <label for="waktuMulai">Waktu Mulai</label>
                                    <div class="row">
                                        <div class="col-sm-5">
                                            <input name="waktuMulai" type="time" class="form-control" id="waktuMulai" value="{{$diklat->waktuMulai}}">
                                        </div>
                                        <div class="col-sm-2">
                                            <label class="form-label my-1" for="waktuSelesai">Sampai</label>
                                        </div>
                                        <div class="col-sm">
                                            <input name="waktuSelesai" type="time" class="form-control" id="waktuSelesai" value="{{$diklat->waktuSelesai}}">
                                        </div>
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <label for="durasi">Durasi </label><span class="text-danger"> *</span>
                                    <input name="durasi" type="number" class="form-control" id="durasi" placeholder="Durasi" required value="{{$diklat->durasi}}">
                                </div>
                                <div class="mb-3">
                                    <label for="tempat">Lokasi</label>
                                    <input name="tempat" type="text" maxlength="255" class="form-control" placeholder="Lokasi" id="tempat" value="{{$diklat->tempat}}">
                                </div>
                                <div class="float-right mt-3">
                                    <button class="btn btn-primary" type="submit">Simpan Perubahan</button>
                                    <a href="{{route('diklat')}}" class="btn btn-secondary">Batal</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    {{-- Sweetalert2 CDN --}}
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
        $('input[name="statusKadaluarsaSertifikat"]').change(function() {
            $('#kadaluarsaSertifikat').attr('disabled', $('input[name="statusKadaluarsaSertifikat"]:checked').length == 1);
        });
    </script>
    @if ($errors->any())
        <script>
            $(document).ready(function(){
                const error = '{{implode(" | ", $errors->all())}}';
                Swal.fire({
                    icon: "error",
                    title: "Error",
                    text: error,
                });
            });
        </script>
    @endif
@endpush

resources/views/diklat/index.blade.php
@extends('layout.app')
@section('title', 'Daftar Diklat')
@section('page', 'Daftar Diklat')

@push('styles')
    {{-- Datatable CSS --}}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.min.css">
@endpush
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <a href="{{route('diklat.create')}}" class="btn btn-primary mb-5">Tambah Diklat</a>
                    <div class="table-responsive">
                        <table id="daftarDiklat" class="table table-bordered text-center" style="width: 100%">
                            <thead>
                              <tr>
                                <th scope="col">No</th>
                                <th scope="col">Nama Diklat</th>
                                <th scope="col">Jenis</th>
                                <th scope="col">Penyelenggara</th>
                                <th scope="col">Jumlah Peserta</th>
                                <th scope="col">Tanggal Mulai</th>
                                <th scope="col">Tanggal Berakhir</th>
                                <th scope="col">Durasi</th>
                                <th scope="col">Tempat</th>
                                <th scope="col">Aksi</th>
                              </tr>
                            </thead>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Delete Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Konfirmasi</h5>
            <button type="button" class="btn-close" onclick="toggleModal()" aria-label="Close"></button>
            </div>
            <div class="modal-body">
            Apakah anda yakin ingin menghapus data?
            </div>
            <div class="modal-footer">
                <form action="" id="modalDeleteForm" method="POST">
                    @csrf
                    <button type="submit" id="modalDeleteButton" class="btn btn-primary">Ya</button>
                </form>
                <button type="button" class="btn btn-secondary" onclick="toggleModal()">Tidak</button>
            </div>
        </div>
        </div>
    </div>
@endsection
@push('scripts')
    {{-- Datatable CDN --}}
    <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap5.min.js"></script>
    {{-- Sweetalert2 CDN --}}
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>


    <script>
        // Datatable diklat
        $(document).ready(function() {
        $('#daftarDiklat').DataTable( {
            "ajax": '{{route('diklat')}}',
            "columns": [
                { "data": "DT_RowIndex" },
                { "data": "nama" },
                { "data": "jenis" },
                { "data": "penyelenggara" },
                { "data": "jumlahPeserta" },
                { "data": "tanggalMulai" },
                { "data": "tanggalSelesai" },
                { "data": "durasi" },
                { "data": "tempat" },
                { "data": "aksi", orderable: false, searchable: false, width: '20rem'},
            ]
        } );

    } );

    // Set delete form action in Delete Modal
    const deleteModal = new bootstrap.Modal(document.getElementById('deleteModal'))
    const toggleModal = () => deleteModal.toggle();
    function showModal (id) {
        toggleModal();
        const url = "{{route('diklat.delete', '')}}";
        $('#modalDeleteForm').attr('action', `${url}/${id}`);
    }
    </script>

    @if (session()->has('message'))
        <script>
            $(document).ready(function(){
                Swal.fire({
                    icon: 'success',
                    title: "{{session('message')}}",
                });
            });
        </script>
    @endif
@endpush

resources/views/layout/app.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <style>
        body {
            background-color: #f8f9fa !important;
        }
        .content {
            margin-top: 2rem;
        }
    </style>
    @stack('styles')
    <title>@yield('title')</title>
  </head>
  <body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="navbar-brand border-right border-secondary mr-0 pr-3">@yield('page')</div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link">Home</a>
                </li>
                @yield('breadcumb')
              </ul>
            </div>
          </nav>

          <div class="content">
            @yield('content')
          </div>

    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{{asset('js/jquery-3.6.0.min.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    @stack('scripts')
  </body>
</html>